title: Lanu Kim
description: Sociology; Computational social science; Inequality; Science of science; Technology and society
logo: /assets/images/image.jpg
cv: /assets/cv/lkim-cv.pdf
show_downloads: true
theme: jekyll-theme-minimal
