title: Lanu Kim
logo: /assets/images/image.jpg
email: mailto:lanukim@kaist.ac.kr
cv: /assets/cv/lkim-cv.pdf
gs: https://scholar.google.com/citations?user=77i0fdMAAAAJ&hl=en&oi=ao
about: #about
projects: #projects-and-publications/working-papers
awards: #awards
agenda: #agenda-on-teaching-and-research
news: #news
teaching: #teaching
theme: jekyll-theme-minimal
